---
apiVersion: "config.istio.io/v1alpha2"
kind: kubernetes
metadata:
  name: attributes
  namespace: test
spec:
  # Pass the required attribute data to the adapter
  source_uid: source.uid | ""
  source_ip: source.ip | ip("0.0.0.0") # default to unspecified ip addr
  destination_uid: destination.uid | ""
  destination_ip: destination.ip | ip("0.0.0.0") # default to unspecified ip addr
  attribute_bindings:
    # Fill the new attributes from the adapter produced output.
    # $out refers to an instance of OutputTemplate message
    source.ip: $out.source_pod_ip
    source.labels: $out.source_labels
    source.namespace: $out.source_namespace
##    source.service: $out.source_service
    source.serviceAccount: $out.source_service_account_name
    destination.ip: $out.destination_pod_ip
##    destination.labels: $out.destination_labels
##    destination.namespace: $out.destination_mamespace
##    destination.service: $out.destination_service
##    destination.serviceAccount: $out.destination_service_account_name
---
apiVersion: config.istio.io/v1alpha2
kind: kubernetesenv
metadata:
  name: kubernetesenv
  namespace: test
spec:

---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: envrule
  namespace: test
spec:
  actions:
  - handler: kubernetesenv.kubernetesenv.test
    instances:
    - attributes.kubernetes.test
