---
apiVersion: "config.istio.io/v1alpha2"
kind: authorization
metadata:
  name: auth
  namespace: test
spec:
 subject:
   user: destination.service
   groups: destination.service
   properties:
    iss: destination.service
 action:
   namespace: destination.namespace | "default"
   service: destination.service | ""
   path: request.path | "/"
   method: request.method | "post"
   properties:
     version: destination.name | ""
---
apiVersion: config.istio.io/v1alpha2
kind: opa
metadata:
  name: handler
  namespace: test
spec:
  policy:
    - |+
      package authz
      default allow=false
      allow = true {
       http.send({"method": "GET", "url": "http://auth.test.svc.cluster.local/auth?a=1","body": {"a": "1" } } , output)
        output.status_code=200
      }
  checkMethod: "data.authz.allow"
  failClose: true
---
apiVersion: config.istio.io/v1alpha2
kind: rule
metadata:
  name: authrule
  namespace: test
spec:
  match: destination.service == "target.test.svc.cluster.local"
  actions:
  - handler: handler.opa.test
    instances:
    - auth.authorization.test





