apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test
  namespace: testpv
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "test"
        version: "0.1"
    spec:
      containers:
      - name: test
        image: tomcat:8
        volumeMounts:
        - mountPath: "/test/data"
          name: testpv
        ports:
        - containerPort: 8080
      volumes:
      - name: testpv
        persistentVolumeClaim:
          claimName: pvctest
