global:
  resolve_timeout: 5m
  smtp_from: "562050688@qq.com"
  smtp_smarthost: "smtp.qq.com:587"
  smtp_auth_username: "562050688@qq.com"
  smtp_auth_password: "umdfkfsuoxfdbefi"

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'email'
receivers:
- name: 'email'
  email_configs:
    - to: "562050688@qq.com"
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
