apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: auth
  name: auth
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: auth
    spec:
      containers:
      - image: ccr.ccs.tencentyun.com/k8s-test/auth:v1
        imagePullPolicy: IfNotPresent
        name: auth
        ports:
        - containerPort: 8888
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  annotations:
    getambassador.io/config: |
      ---
      apiVersion: ambassador/v0
      kind: Mapping
      name: auth-mapping
      prefix: /auth
      service: auth:8888
spec:
  type: ClusterIP
  selector:
    run: auth
  ports:
  - port: 8888
    name: auth-port
    targetPort: 8888
